CREATE TABLE `peppol_electronic_invoice_header_data`
(
    `UBLVersionID`                                                               varchar(4) NOT NULL,       --<cbc> "2.1"
    `CustomizationID`                                                            varchar(100) NOT NULL,     --<cbc> "urn:cen.eu:en16931:2017#conformant#urn:fdc:peppol.eu:2017:poacc:billing:international:sg:3.0"
    `ProfileID`                                                                  varchar(100) NOT NULL,     --<cbc> "urn:fdc:peppol.eu:2017:poacc:billing:01:1.0"
    `ID`                                                                         varchar(10) NOT NULL,      --<cbc> "F012345"
    `IssueDate`                                                                  varchar(80) DEFAULT NULL,  --<cbc> "2018-12-01"
    `DueDate`                                                                    varchar(80) DEFAULT NULL,  --<cbc> "2019-01-01"
    `InvoiceTypeCode`                                                            varchar(3) DEFAULT NULL,   --<cbc> "380"
    `Note`                                                                       varchar(100) DEFAULT NULL, --<cbc> "Ordered at trade show"
    `DocumentCurrencyCode`                                                       varchar(3) DEFAULT NULL,   --<cbc> "SGD"
    `AccountingCost`                                                             varchar(25) DEFAULT NULL,  --<cbc> "102035"
    `BuyerReference`                                                             varchar(100) DEFAULT NULL, --<cbc> "123"
    `InvoicePeriodStartDate`                                                     varchar(80) DEFAULT NULL,  --<cbc/cac:InvoicePeriod> "2018-11-01"
    `InvoicePeriodEndDate`                                                       varchar(80) DEFAULT NULL,  --<cbc/cac:InvoicePeriod> "2018-11-30"
    `OrderReferenceID`                                                           varchar(10) DEFAULT NULL,  --<cbc/cac:OrderReference> "123"
    `OrderReferenceSalesOrderID`                                                 varchar(10) DEFAULT NULL,  --<cbc/cac:OrderReference> "123"
    `BillingReferenceInvoiceDocumentReferenceID`                                 varchar(10) DEFAULT NULL,  --<cbc/cac:BillingReferenceInvoiceDocumentReference/cac:BillingReference> "invnr002"
    `BillingReferenceInvoiceDocumentReferenceIssueDate`                          varchar(80) DEFAULT NULL,  --<cbc/cac:BillingReferenceInvoiceDocumentReference/cac:BillingReference> "2018-06-01"
    `DespatchDocumentReferenceID`                                                varchar(10) DEFAULT NULL,  --<cbc/cac:DespatchDocumentReference> "987"
    `ReceiptDocumentReferenceID`                                                 varchar(10) DEFAULT NULL,  --<cbc/cac:ReceiptDocumentReference> "654"
    `OriginatorDocumentReferenceID`                                              varchar(10) DEFAULT NULL,  --<cbc/cac:OriginatorDocumentReference> "753"
    `ContractDocumentReferenceID`                                                varchar(10) DEFAULT NULL,  --<cbc/cac:ContractDocumentReference> "Contract321"
    `AdditionalDocumentReferenceID`                                              varchar(10) DEFAULT NULL,  --<cbc/cac:AdditionalDocumentReference> "doc1"
    `AdditionalDocumentReferenceDocumentDescription`                             varchar(100) DEFAULT NULL,  --<cbc/cac:AdditionalDocumentReference> "Usage breakdown"
    `AdditionalDocumentReferenceAttachmentExternalReferenceURI`                  varchar(50) DEFAULT NULL,  --<cbc/cac:AdditionalDocumentReferenceAttachmentExternalReference/cac:AdditionalDocumentReference> "http://www.salescompany.be/breakdown001.html"
    `AdditionalDocumentReferenceID`                                              varchar(10) DEFAULT NULL,  --<cbc/cac:AdditionalDocumentReference> "doc2"
    `AdditionalDocumentReferenceDocumentDescription`                             varchar(100) DEFAULT NULL,  --<cbc/cac:AdditionalDocumentReference> "Usage summary"
    `AdditionalDocumentReferenceAttachmentEmbeddedDocumentBinaryObject`          varchar(80) DEFAULT NULL,  --filename="report.csv" mimeCode="text/csv"<cbc/cac:AdditionalDocumentReferenceAttachment/cac:AdditionalDocumentReference> "aHR0cHM6Ly90ZXN0LXZlZmEuZGlmaS5uby9wZXBwb2xiaXMvcG9hY2MvYmlsbGluZy8zLjAvYmlzLw"
    `AdditionalDocumentReferenceID`                                              varchar(10) DEFAULT NULL,  --schemeID="ABZ"<cbc/cac:AdditionalDocumentReference> "951"
    `AdditionalDocumentReferenceDocumentTypeCode`                                varchar(3) DEFAULT NULL,   --<cbc/cac:AdditionalDocumentReference> "130"
    `ProjectReferenceID`                                                         varchar(10) DEFAULT NULL,  --<cbc/cac:ProjectReference> "321"
    `AccountingSupplierPartyPartyEndpointID `                                    varchar(10) DEFAULT NULL,  --schemeID="0088"<cbc/cac:AccountingSupplierPartyParty/cac:AccountingSupplierParty> "5790000436064"
    `AccountingSupplierPartyPartyPartyIdentificationID`                          varchar(10) DEFAULT NULL,  --schemeID="0035"<cbc/cac:AccountingSupplierPartyPartyPartyIdentification/cac:AccountingSupplierPartyParty/cac:AccountingSupplierParty> "5790000436071"
    `AccountingSupplierPartyPartyPartyTaxSchemeCompanyID`                        varchar(10) DEFAULT NULL,  --<cbc/cac:AccountingSupplierPartyPartyPartyTaxScheme/cac:AccountingSupplierPartyParty/cac:AccountingSupplierParty> "M2-1234567-K"
    `AccountingSupplierPartyPartyPartyTaxSchemeTaxSchemeID`                      varchar(10) DEFAULT NULL,  --<cbc/cac:AccountingSupplierPartyPartyPartyTaxSchemeTaxScheme/cac:AccountingSupplierPartyPartyPartyTaxScheme/cac:AccountingSupplierPartyParty/cac:AccountingSupplierParty> "GST"
    `AccountingCustomerPartyPartyEndpointID `                                    varchar(10) DEFAULT NULL,  --schemeID="0088"<cbc/cac:AccountingCustomerPartyParty/cac:AccountingCustomerParty> "5790000436071"
    `AccountingCustomerPartyPartyPartyIdentificationID`                          varchar(10) DEFAULT NULL,  --schemeID="0035"<cbc/cac:AccountingCustomerPartyPartyPartyIdentification/cac:AccountingCustomerPartyParty/cac:AccountingCustomerParty> "345KS5324"
    `PayeePartyPartyIdentificationID `                                           varchar(10) DEFAULT NULL,  --schemeID="0035"<cbc/cac:PayeePartyPartyIdentification/cac:PayeeParty> "Payee123"
    `TaxRepresentativePartyPartyTaxSchemeCompanyID`                              varchar(10) DEFAULT NULL,  --<cbc/cac:TaxRepresentativePartyPartyTaxScheme/cac:TaxRepresentative> "FR98746"
    `TaxRepresentativePartyPartyTaxSchemeTaxSchemeID`                            varchar(10) DEFAULT NULL,  --<cbc/cac:TaxRepresentativePartyPartyTaxSchemeTaxScheme/cac:TaxRepresentativePartyPartyTaxScheme/cac:TaxRepresentative> "GST"
    `DeliveryActualDeliveryDate`                                                 varchar(80) DEFAULT NULL,  --<cbc/cac:Delivery> "2010-08-31"
    `DeliveryDeliveryLocationID`                                                 varchar(10) DEFAULT NULL,  --schemeID="0035"<cbc/cac:DeliveryDeliveryLocation/cac:Delivery> "6754238987648"
    `PaymentMeansPaymentMeansCode`                                               varchar(2) DEFAULT NULL,   --name="Bank transfer"<cbc/cac:PaymentMeans> "30"
    `PaymentMeansPaymentID`                                                      varchar(10) DEFAULT NULL,  --<cbc/cac:PaymentMeans> "gr12345"
    `TaxTotalTaxAmount                                                           varchar(10) DEFAULT NULL,  --currencyID="SGD"`<cbc/cac:TaxTotal> "2374.05"
    `TaxTotalTaxSubtotalTaxableAmount`                                           varchar(10) DEFAULT NULL,  --currencyID="SGD"<cbc/cac:TaxTotalTaxSubtotal/cac:TaxTotal> "33915.00"
    `TaxTotalTaxSubtotalTaxAmount`                                               varchar(10) DEFAULT NULL,  --currencyID="SGD"<cbc/cac:TaxTotalTaxSubtotal/cac:TaxTotal> "2374.05"
    `TaxTotalTaxSubtotalTaxCategoryID`                                           varchar(10) DEFAULT NULL,  --<cbc/cac:TaxTotalTaxSubtotalTaxCategory/cac:TaxTotalTaxSubtotal/cac:TaxTotal> "SR"
    `TaxTotalTaxSubtotalTaxCategoryPercent`                                      varchar(1) DEFAULT NULL,   --<cbc/cac:TaxTotalTaxSubtotalTaxCategory/cac:TaxTotalTaxSubtotal/cac:TaxTotal> "7"
    `TaxTotalTaxSubtotalTaxCategoryTaxSchemeID`                                  varchar(10) DEFAULT NULL,  --<cbc/cac:TaxTotalTaxSubtotalTaxCategoryTaxScheme/cac:TaxTotalTaxSubtotalTaxCategory/cac:TaxTotalTaxSubtotal/cac:TaxTotal> "GST"
    `LegalMonetaryTotalLineExtensionAmount`                                      varchar(10) DEFAULT NULL,  --currencyID="SGD"`<cbc/cac:LegalMonetaryTotal> "33915.00"
    `LegalMonetaryTotalTaxExclusiveAmount`                                       varchar(10) DEFAULT NULL,  --currencyID="SGD"`<cbc/cac:LegalMonetaryTotal> "33915.00"
    `LegalMonetaryTotalTaxInclusiveAmount`                                       varchar(10) DEFAULT NULL,  --currencyID="SGD"`<cbc/cac:LegalMonetaryTotal> "36289.05"
    `LegalMonetaryTotalAllowanceTotalAmount`                                     varchar(10) DEFAULT NULL,  --currencyID="SGD"`<cbc/cac:LegalMonetaryTotal> "0.00"
    `LegalMonetaryTotalChargeTotalAmount`                                        varchar(10) DEFAULT NULL,  --currencyID="SGD"`<cbc/cac:LegalMonetaryTotal> "0.00"
    `LegalMonetaryTotalPrepaidAmount`                                            varchar(10) DEFAULT NULL,  --currencyID="SGD"`<cbc/cac:LegalMonetaryTotal> "0.00"
    `LegalMonetaryTotalPayableRoundingAmount`                                    varchar(10) DEFAULT NULL,  --currencyID="SGD"`<cbc/cac:LegalMonetaryTotal> "0.0"
    `LegalMonetaryTotalPayableAmount`                                            varchar(10) DEFAULT NULL,  --currencyID="SGD"`<cbc/cac:LegalMonetaryTotal> "36289.05"
    PRIMARY KEY (`UBLVersionID`, `CustomizationID`, `ProfileID`, `ID`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
